cliDefaults:
  run:
    plan: false
    sequential: true
excludes:
  - '*.local'
  - CHANGELOG.md
  - docs
  - package-lock.json
scripts:
  typecheck: npm run typecheck
  lint: npm run lint:fix
  test: npm run test -- --no-color
  bench: npm run bench -- --no-color
  build: npm run build
  docs: npm run docs -- --emit none
  knip: npm run knip
patchOpenCommand: code -g {file}
stanPath: .stan
includes: []
